require: rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*.rb'
    - 'config/environments/production.rb'
Rails:
  Enabled: true

# Accept single-line methods with no body
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Top-level documentation of classes and modules are needless
Style/Documentation:
  Enabled: false

# Allow to chain of block after another block that spans multiple lines
Style/MultilineBlockChain:
  Enabled: false

# Allow `->` literal for multi line blocks
Style/Lambda:
  Enabled: false

# Both nested and compact are okay
Style/ClassAndModuleChildren:
  Enabled: false

# Specifying param names is unnecessary
Style/SingleLineBlockParams:
  Enabled: false

# Allow using `{...}` for anytime
Style/BlockDelimiters:
  Enabled: false

# Prefer Kernel#sprintf
Style/FormatString:
  EnforcedStyle: sprintf

# Maximum line length
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

# Maximum method length
Metrics/MethodLength:
  Max: 20

# Tuned to MethodLength
Metrics/AbcSize:
  Max: 30

# Prefer double_quotes strings unless your string literal contains escape chars
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Put a comma after the last item of a multiline array
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Put a comma after the last item of a multiline hash
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Metrics/ClassLength:
  Max: 150

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 8

# Enable using rescue in its modifier form.
Style/RescueModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
